AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
