AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: false

Style/Documentataion:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false
