# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

module ::Rake::TaskLib; end
module Gem::Ext::BuildError; end
module URI::File; end
